#!/bin/bash
# Usage: sh cleanup.sh

# clean the folders created in the run of the script to prepare the next run
# remove folders
rm --recursive -f ./results
rm --recursive -f ./logs
rm --recursive -f ./input/aggregations
rm --recursive -f ./feature_metrices
rm --recursive -f ./ef_gen_tr
rm --recursive -f ./ef_gen_ho
rm --recursive -f ./edge_tf_true
rm --recursive -f ./edge_tf_tr

# create folders that are not generated by the script
mkdir ./logs
